spring:
  application:
    name: mywork-be
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/mywork_db
    username: root
    password: mywork2503
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: messages/messages
    fallback-to-system-locale: false
  cloud:
    aws:
      s3:
        region: us-east-1 # TODO 운영용은 별도로 선언
      credentials:
        access-key: test # TODO 운영용은 별도로 선언
        secret-key: test # TODO 운영용은 별도로 선언
  output:
    ansi:
      enabled: never
management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,prometheus"  # 혹은 "*"로 모든 엔드포인트 오픈 가능
company:
  page:
    size: 10
  upload:
    duration: 3m
member:
  page:
    size: 10
post:
  page:
    size: 10
  upload:
    bucket-name: mywork-upload-bucket
    duration: 3m
    endpoint: http://localhost:4566
  attachment:
    max-count: 3
  issued-id:
    created-limit-hour: 24
    delete:
      cron: 0 0 4 * * *
project:
  page:
    size: 10
review:
  page:
    size: 10
dashboard:
  page:
    size: 5
activityLog:
  page:
    size: 10
notification:
  page:
    size: 10
jwt:
  access-token:
    private-key: 126cab8a5d9087a27be4e2a0599682e2bab38e80201d1befa2dd9d55ecbdeac58bab0c84301ad9f9f8a71836825e5a7214e7a9fb17a8578418de6cfe9a15cbc7
    expiration: 3600000
  refresh-token:
    private-key: 408a96ae4affd8bce03d11385d9a8dfbd4c0cbc9c5a83675864192dbb50eaa965acf2ef84e60bb1a38798f612caed4f383466a4be14957bf87370b62be71c2e1
    expiration: 86400000

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

security:
  allow:
    origins:
      - http://localhost:3000
      - https://d16zykr4498a0c.cloudfront.net
      - https://kbe-mywork.com
      - https://www.kbe-mywork.com
      - http://mywork-frontend-bucket-only-s3.s3-website.ap-northeast-2.amazonaws.com
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    headers:
      - '*'
    credential: true
