version: '3.8'
services:
  mysql:
    container_name: 'mywork_rdb'
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'mywork2503'
      MYSQL_DATABASE: mywork_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
