name: mywork ci/cd workflows

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: (1) Set up Docker
        uses: docker/setup-docker-action@v4
      - name: (2) Checkout sources
        uses: actions/checkout@v4
      - name: (3) Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: (4) Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: (5) Build with Gradle
        run: ./gradlew clean build
      - name: (6) Zip artifact
        run: |
          mkdir -p deploy
          cp build/libs/mywork-be-0.0.1-SNAPSHOT.jar deploy/mywork-be-0.0.1-SNAPSHOT.jar
          cp appspec.yml deploy/
          cp -r scripts/ deploy/
      - name: (7) Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: (8) Upload to S3
        run: |
          aws deploy push \
          --application-name ${{ vars.DEPLOY_APP_NAME }} \
          --ignore-hidden-files \
          --s3-location s3://${{ vars.BUILD_BUCKET_NAME }}/$GITHUB_SHA.zip \
          --source ./deploy
      - name: (9) Deploy to EC2 via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ vars.DEPLOY_APP_NAME }}  \
            --deployment-group-name ${{ vars.DEPLOYMENT_GROUP_NAME }}  \
            --s3-location bucket=${{ vars.BUILD_BUCKET_NAME }},key=$GITHUB_SHA.zip,bundleType=zip \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --description "Mywork CD by GitHub Actions"
