name: pr-test-ci.yml

on:
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: (1) Set up Docker
        uses: docker/setup-docker-action@v4
      - name: (2) Checkout sources
        uses: actions/checkout@v4
      - name: (3) Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: (4) Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: (5) Build with Gradle
        run: ./gradlew clean test
      - name: (6) 테스트 결과를 PR 코멘트로 출력
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: (7) 테스트 실패 시, 오류가 발생한 코드 라인에 코멘트 추가
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
